accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns = [
    url(r"^signup/$",views.SignUpView.as_view(),name = "signup"),
    url(r"^signin/$",views.LoginView.as_view(),name = "signin"),
    url(r"^signout/$",views.LogoutView.as_view(),name = "signout"),
]

airplane_monitoring/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from django.shortcuts import redirect,reverse

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',lambda request : redirect(reverse("accounts:signin"))),
    url(r'accounts/',include('accounts.urls')),
    url(r'tracking/',include('tracking.urls')),
    
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

tracking/urls.py
from django.conf.urls import url
from . import views
app_name = 'tracking'
urlpatterns = [
    url(r"^create/$",views.TrackingCreateView.as_view(),name = "create_tracking"),
    url(r"^list/$",views.TrackingListView.as_view(),name = "list_tracking"),
    url(r"^disable/(?P<pk>\d+)/$",views.DisableTrackingView.as_view(),name = "disable_tracking"),
    url(r"^enable/(?P<pk>\d+)/$",views.EnableTrackingView.as_view(),name = "enable_tracking"),
    url(r"^delete/(?P<pk>\d+)/$",views.TrackingDeleteView.as_view(),name = "delete_tracking"),
]

tracking/models.py
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from accounts.models import CustomUser
from django.shortcuts import reverse
from django.core.validators import MinValueValidator
# Create your models here.

class Flight(models.Model):
    """Flights informations model
    """    
    origin = models.CharField(max_length=200)
    destination = models.CharField(max_length=200)
    flight_number = models.CharField(max_length=200,unique=True)
    airline = models.CharField(max_length=200)
    schedule_delay = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1)])
    informations_file = models.FileField(storage=FileSystemStorage(location=settings.MEDIA_ROOT), 
                                         upload_to='flights_info',
                                         default='flights_info/crawler_result.json')
    users = models.ManyToManyField(CustomUser,through='FlightUser',related_name='flights',symmetrical=False)
    def __str__(self):
        return self.flight_number
    
class FlightStatusManager(models.Manager):
    """ Custom Flight Status manager """
    def create(self,*args,**kwargs):
        """FlightStatus create manager customized to count and save the position of object in the crawled objects
        """        
        if 'position' not in kwargs:
            queryset = self.filter(flight__flight_number=kwargs['flight_number']).order_by('-date')
            if queryset.exists():
                position = queryset[0].position + 1
                kwargs['position']=position
        return super(FlightStatusManager,self).create(*args,**kwargs)
    
class FlightStatus(models.Model):
    """Status of flight resulted by crawler
    """    
    flight = models.ForeignKey(Flight,on_delete=models.CASCADE)
    position = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    longitude = models.DecimalField(max_digits=6, decimal_places=3)
    latitude = models.DecimalField(max_digits=6, decimal_places=3)
    arrival_time = models.DateTimeField(auto_now_add=False)
    
    objects = FlightStatusManager()
    
    def __str__(self):
        return self.flight.flight_number + " - " + str(self.position)
    
class FlightUser(models.Model):
    """Flight's users through model to create connection between users and flights
    """    
    user = models.ForeignKey(CustomUser,related_name="user_flights",on_delete=models.CASCADE)
    flight = models.ForeignKey(Flight,related_name = "flight_users",on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    schedule_delay = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1)])
    
    class Meta:
        unique_together = ("user","flight")
    
        
    def get_absolute_url(self):
        return reverse('tracking:list_tracking')

    def __str__(self):
        return self.user.username+","+self.flight.flight_number

tracking/forms.py
from django import forms
from . import models

class Tracking(forms.ModelForm):
    """Aiplane Tracking adding form """
    class Meta:
        model = models.FlightUser
        fields = ("flight",'schedule_delay')
        widgets = {"flight":forms.Select()}
        help_texts = {"schedule_delay": "In minutes"}

tracking/views.py
from django.shortcuts import render,reverse
from django.views.generic import CreateView, ListView,DeleteView,View
from . import models
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

class TrackingCreateView(LoginRequiredMixin,CreateView):
    """Create a tracking scheduler task"""
    form_class = forms.Tracking
    template_name  = "tracking/create.html"
    
    def form_valid(self,form):
        flight_user = models.FlightUser.objects.filter(user=self.request.user,flight = form.cleaned_data['flight'])
        if flight_user.exists():
            flight_user = flight_user.first()
            flight_user.status = True
            flight_user.schedule_delay = form.cleaned_data['schedule_delay']
            flight_user.save()
            return HttpResponseRedirect(reverse("tracking:list_tracking"))
        self.object=form.save(commit=False)
        self.object.user= self.request.user
        self.object.status = True
        return super(TrackingCreateView,self).form_valid(form)

class TrackingListView(LoginRequiredMixin,ListView):
    """List of tracking tasks"""
    template_name = "tracking/list.html"
    model = models.FlightUser
    context_object_name = "user_flights"
    
    def get_queryset(self,*args,**kwargs):
        
        return super(TrackingListView,self).get_queryset(*args,**kwargs).select_related("flight").filter(user=self.request.user).order_by('-status')

class DisableTrackingView(LoginRequiredMixin,View):
    """Disable tracking task """
    def get(self, request, *args, **kwargs):
        flight_status=models.FlightUser.objects.filter(pk=kwargs['pk'])
        if flight_status.exists():
            flight_status = flight_status.first()
            flight_status.status=False
            flight_status.save()
        return  HttpResponseRedirect(reverse("tracking:list_tracking"))

class EnableTrackingView(LoginRequiredMixin,View):
    """Disable tracking task """
    def get(self, request, *args, **kwargs):
        flight_status=models.FlightUser.objects.filter(pk=kwargs['pk'])
        if flight_status.exists():
            flight_status = flight_status.first()
            flight_status.status=True
            flight_status.save()
        return  HttpResponseRedirect(reverse("tracking:list_tracking"))
    
class TrackingDeleteView(LoginRequiredMixin,DeleteView):
    """Delete tracking task"""
    model = models.FlightUser
    success_url = reverse_lazy("tracking:list_tracking")

tracking/templates/tracking/create.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<div class="signup-content tracking-create">
    <div class="tracking-form">
        <form method="POST" class="register-form" id="tracking-form">
            <h2>Start Tracking</h2>
            {% csrf_token %}
            {{ form.as_p }}         
            <div class="form-submit">
                <input type="reset" value="Reset All" class="submit" name="reset" id="reset" />
                <input type="submit" value="Submit Form" class="submit" name="submit" id="submit" />
            </div>
        </form>
    </div>
</div>

{% endblock %}

tracking/templates/tracking/list.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<table id="table" class="table table-hover table-mc-light-blue">
  <thead>
    <tr>
      <th></th>
      <th scope="col">Flight Number</th>
      <th scope="col">Airline</th>
      <th scope="col">Origin</th>
      <th scope="col">Destination</th>
      <th scope="col">Schedule delay(min)</th>
      <th scope="col">Notification</th>
      <th scope="col">Enable/Disable</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for uf in user_flights %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{uf.flight.flight_number}}</td>
      <td>{{uf.flight.airline}}</td>
      <td>{{uf.flight.origin}}</td>
      <td>{{uf.flight.destination}}</td>
      <td>{{uf.schedule_delay}}</td>
      <td>{% if uf.status %}<span style="color:green"> On</span> {%else%} <span style="color:red"> OFF</span> {%endif%}</td>
      <td>{% if uf.status %}<a href="{% url 'tracking:disable_tracking' pk=uf.pk %}">Disable</a>{%else%}<a href="{% url 'tracking:enable_tracking' pk=uf.pk %}">Enable</a>{%endif%}</td>
      <td>
      <form method="POST" action="{% url 'tracking:delete_tracking' pk=uf.pk %}">
        {% csrf_token %}<input style="cursor:pointer; font-size:10px; background-color:coral; padding: 11px 0px;" type="submit" value="DELETE">
     </form>
    </td>
    </tr>
    {% empty %} 
    <tr>
      <td>No item in the list!</td>
    
    </tr>

    {% endfor %}
  </tbody>
</table>






{% endblock %}