accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns = [
    url(r"^signup/$",views.SignUpView.as_view(),name = "signup"),
    url(r"^signin/$",views.LoginView.as_view(),name = "signin"),
    url(r"^signout/$",views.LogoutView.as_view(),name = "signout"),
]

airplane_monitoring/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from django.shortcuts import redirect,reverse

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',lambda request : redirect(reverse("accounts:signin"))),
    url(r'accounts/',include('accounts.urls')),
    url(r'tracking/',include('tracking.urls')),
    
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User
from django.utils import timezone
from django.shortcuts import reverse

class CustomUser(AbstractUser):
    """Updated user object with new params and methods

    Args:
        AbstractUser ([obj]): inherit the Abstractuser class

    """
    phone_number = models.CharField(max_length=11,unique=True,null=True,blank=True)
    birth_date = models.DateTimeField(blank=True,null=True)
    
    def __str__(self):
        """model objects displaying names

        Returns:
            [str]: user email
        """
        return self.email
    
    def get_absolute_url(self):
        return reverse('accounts:signin')

accounts/forms.py
from django import forms
from . import models
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm


class UserSignUpForm(UserCreationForm):
    """Form for user signing up,inherited from django base UserCreationForm and changed some attributes

    Args:
        UserCreationForm ([object]): django base UserCreationForm
    """    
    class Meta:
        model = models.CustomUser
        fields=('username','first_name','last_name','email','phone_number')
        
    def __init__(self, *args, **kwargs):
        super(UserSignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs={'class':'form-row'}
        self.fields['username'].help_text = None
        self.fields['first_name'].widget.attrs={'class':'form-row'}
        self.fields['last_name'].widget.attrs={'class':'form-row'}
        self.fields['email'].widget.attrs={'class':'form-row'}
        self.fields['password1'].widget.attrs={'class':'form-row'}
        self.fields['password1'].help_text = None
        self.fields['password2'].widget.attrs={'class':'form-row'}
        self.fields['password2'].help_text = None
        self.fields['phone_number'].widget.attrs={'class':'form-row'}
        
        
class LoginForm(AuthenticationForm):
    """Form for login,inherited from django authenticationForm to change some attributes

    Args:
        AuthenticationForm ([object]): django base authentication form
    """    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'autofocus': False})

accounts/views.py
from django.shortcuts import render,reverse
from django.views.generic import CreateView, FormView,View
from . import models
from . import forms
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from abc import ABCMeta


class RedirectAuthenticationMixin(metaclass = ABCMeta):
    """Mixin for signin and login page to redirect if user is authenticated

    Args:
        metaclass ([type], optional): [description]. Defaults to ABCMeta.
    """    
    def get(self,*args, **kwargs):
        if self.request.user.is_authenticated():
            return HttpResponseRedirect(reverse("tracking:list_tracking"))
        return super().get(*args, **kwargs)
    
class SignUpView(RedirectAuthenticationMixin,CreateView):
    """Signing Up view
    """    
    model = models.CustomUser
    template_name = "signup.html"
    form_class = forms.UserSignUpForm
    
class LoginView(RedirectAuthenticationMixin,FormView):
    """Login View to handle user login """    
    form_class = forms.LoginForm
    template_name = "login.html"
    def form_valid(self,form):
        
        auth_login(self.request,form.get_user())
        return super(LoginView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse('tracking:list_tracking')
    
class LogoutView(LoginRequiredMixin,View):
    """ User logout view """
    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return  HttpResponseRedirect(reverse("accounts:signin"))

accounts/templates/login.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<div class="signup-content">
    <div class="signup-img">
        <img src="{% static 'images/signup-img.jpg' %}" alt="">
    </div>
    <div class="signup-form">
        <form method="POST" class="register-form" id="login-form">
            <h2>User Login</h2>
            {% csrf_token %}
            {{ form.as_p }}         
            <div class="form-submit">
                <input type="reset" value="Reset All" class="submit" name="reset" id="reset" />
                <input type="submit" value="Login" class="submit" name="submit" id="submit" />
            </div>
            <p>Don't have an account? <a href="{% url 'accounts:signup' %}">Sign up</a></p>
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/signup.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<div class="signup-content">
    <div class="signup-img">
        <img src="{% static 'images/signup-img.jpg' %}" alt="">
    </div>
    <div class="signup-form">
        <form method="POST" class="register-form" id="register-form">
            <h2>User Registration</h2>

            {% csrf_token %}
            {{ form.as_p }}         
            <div class="form-submit">
                <input type="reset" value="Reset All" class="submit" name="reset" id="reset" />
                <input type="submit" value="Submit Form" class="submit" name="submit" id="submit" />
            </div>
            <p>Already have an account? <a href="{% url 'accounts:signin' %}">Sign in</a></p>
        </form>
    </div>
</div>

{% endblock %}