accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns = [
    url(r"^signup/$",views.SignUpView.as_view(),name = "signup"),
    url(r"^signin/$",views.LoginView.as_view(),name = "signin"),
    url(r"^signout/$",views.LogoutView.as_view(),name = "signout"),
]

airplane_monitoring/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from django.shortcuts import redirect,reverse

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',lambda request : redirect(reverse("accounts:signin"))),
    url(r'accounts/',include('accounts.urls')),
    url(r'tracking/',include('tracking.urls')),
    
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

tracking/urls.py
from django.conf.urls import url
from . import views
app_name = 'tracking'
urlpatterns = [
    url(r"^create/$",views.TrackingCreateView.as_view(),name = "create_tracking"),
    url(r"^list/$",views.TrackingListView.as_view(),name = "list_tracking"),
    url(r"^disable/(?P<pk>\d+)/$",views.DisableTrackingView.as_view(),name = "disable_tracking"),
    url(r"^enable/(?P<pk>\d+)/$",views.EnableTrackingView.as_view(),name = "enable_tracking"),
    url(r"^delete/(?P<pk>\d+)/$",views.TrackingDeleteView.as_view(),name = "delete_tracking"),
]

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
</head>
<body>
    {% if user.is_authenticated %}
<header>
    <div class="container">
        <ul>
            <li><a href="{% url 'tracking:list_tracking' %}">List</a></li>

            <li><a href="{% url 'tracking:create_tracking' %}">Create</a></li>
            <li><a href="{% url 'accounts:signout' %}">Logout</a></li>
        </ul>
    </div>
</header>
{%endif%}
    <div class="main">
        <div class="container">
            {% block content %}{% endblock %}
        </div>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>